version: "3.8"
services:
    db:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=node_shop
            - MONGO_INITDB_ROOT_PASSWORD=12345
        ports:
            - "27017:27017"
        volumes:
            - ./db:/data/db
        networks:
            - node
    app:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        container_name: node_shop
        ports:
            - "8080:8080"
        depends_on:
            - db
        stdin_open: true
        volumes:
            - ./:/app
            - /app/node_modules
        networks:
            - node
networks:
    node:
